### PR TITLE
GeoIP for Queensland Regions

### PR DESCRIPTION
**Pull request by jakegaia**
Takes user's IP location and designates the Queensland Region they are
situated in

### CODE REVIEW

**Comment by mostro20** [comment]
Haven't had a chance to test (being in Tasmania makes it a bit hard :-) ), but looks like it would work quite nicely. 

My only concern would the "qld-regions.js" file is 1.6MB, which is pretty big for a text file - can only assume it's that size as the polygons contain a lot of complexity. But this does mean the user has to download 1.6mb before the script can run, which increases the size of Qld Gov home page by 50%. Do you think we might be able to "smooth" out some of polygons to decrease file size?

**Comment by jakegaia** [comment]
Those polys have been smoothed. It can be difficult for the land boundaries though, as you end up with gaps and overlaps. Going to try a couple new approaches, which should solve that issue and decrease the size even further.
As for the tool, AD has run through a new approach that seems to be working on his side, so I'll update the git code once we have a smaller geojson.

**Comment by mostro20** [comment]
Hey Jake - cool 248kb, much nicer. Also like the convention of calling it "simple" so that if someone wanted to run it as a more precise option we have the full sized file with more exact boundaries. Will merge the PR and see if we can get some people around the state to test it out.

**Comment by jakegaia** [comment]
If you could review it too that would be great. The new code changes are from AD.

**Pull request merged**
